# Generated by Django 4.0.6 on 2023-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pp',
            field=models.ImageField(default='thumbnai/noimage.png', upload_to='pp'),
        ),
    ]
