# Generated by Django 4.0.6 on 2023-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0014_alter_categorys_options_alter_manga_options_and_more'),
        ('Users', '0006_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(null=True, to='Manga.manga'),
        ),
    ]
