# Generated by Django 4.0.6 on 2023-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0002_chapter_chapter_number_chapter_chapter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_image',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_url',
            field=models.URLField(default='www.example.com'),
        ),
    ]
