# Generated by Django 4.0.6 on 2023-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0009_alter_chapter_relase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_title', models.CharField(max_length=255)),
                ('duyuru_description', models.TextField(max_length=1024)),
            ],
        ),
    ]
