# Generated by Django 4.0.6 on 2023-01-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_url',
            field=models.URLField(default='null'),
        ),
        migrations.AlterField(
            model_name='fansub',
            name='fansub_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
