# Generated by Django 4.0.6 on 2023-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0005_alter_manga_manga_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_views',
            field=models.IntegerField(default=0),
        ),
    ]
