# Generated by Django 4.0.6 on 2023-03-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0010_duyuru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyuru',
            old_name='duyuru_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='duyuru',
            old_name='duyuru_title',
            new_name='title',
        ),
    ]
