# Generated by Django 4.0.6 on 2023-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0013_categorys_mangacategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['manga_name']},
        ),
        migrations.RenameField(
            model_name='categorys',
            old_name='Category_name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_categorys',
            field=models.ManyToManyField(to='Manga.categorys'),
        ),
        migrations.DeleteModel(
            name='MangaCategory',
        ),
    ]
