# Generated by Django 4.0.6 on 2023-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0014_alter_categorys_options_alter_manga_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(max_length=1024)),
                ('A', models.CharField(max_length=2048)),
            ],
        ),
    ]
