# Generated by Django 4.0.6 on 2023-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pp',
            field=models.ImageField(default='thumbnail/noimage.png', upload_to='pp'),
        ),
    ]
