# Generated by Django 4.0.6 on 2023-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_pp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pp',
            new_name='profile_picture',
        ),
    ]
