# Generated by Django 4.0.6 on 2023-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0015_sss'),
        ('Users', '0007_alter_customuser_bio_alter_customuser_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(to='Manga.manga'),
        ),
    ]
